More fine grained routing key settings for messages
jenkinsci/mq-notifier-plugin pull request #49
Opened 2023-11-02 12:27 UTC by TWestling

Currently, the only way to choose a routing key is to set one which will be used for every message.
This pull request adds an automatic setting of routing keys, where each method that publishes messages gets one based on the method. For details on the automatic routing keys, look at: src/main/webapp/help-automatic-routing-key.html

### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2023-11-12 21:58 UTC, magnusbaeck requested changes
Code LGTM, just a few comment nits that we might as well fix.

Side note: We're not covering this new functionality in any tests.

2023-11-12 21:58 UTC, magnusbaeck commented on src/main/java/com/sonymobile/jenkins/plugins/mq/mqnotifier/MQNotifierConfig.java
> +     * Sets the routing key.
```suggestion
     * Sets the routing key provider ("AUTO" or "MANUAL").
```

2023-11-12 21:58 UTC, magnusbaeck commented on src/main/java/com/sonymobile/jenkins/plugins/mq/mqnotifier/MQNotifierConfig.java
> +     * Gets the routing key provider, either "auto" or "manual".
```suggestion
     * Gets the routing key provider, either "AUTO" or "MANUAL".
```
Should we use constants for these values?

2023-11-12 21:58 UTC, magnusbaeck commented on src/main/java/com/sonymobile/jenkins/plugins/mq/mqnotifier/pipeline/MQMessageStep.java
> +            MQConnection.getInstance().publish(json, "publishMQMessage");
A potential follow-up could be to add the routing key as an optional argument to the pipeline step.

2023-11-12 21:58 UTC, magnusbaeck commented on src/main/webapp/help-manual-routing-key.html
> +<p>With this setting, every message sent will have the routing key specified in the "Routing Key" field.</p>
Missing newline at EOF.

2023-11-15 12:11 UTC, TWestling commented
Added tests + fixed nits. Also added the optional routing key for the message step since it felt like very low hanging fruit.

2023-11-15 12:55 UTC, magnusbaeck approved these changes

2023-11-15 12:55 UTC, magnusbaeck commented on src/test/java/com/sonymobile/jenkins/plugins/mq/mqnotifier/PluginTest.java
> +
Extra blank line.

2023-11-15 14:12 UTC, merged